build_dir: /home/user/v2ci_build # Directory where rootfs environments, logs and build artifacts will be stored (the user must have write permissions here)

projects:
  - name: sshlirp
    target_dir: /home/user/sshlirp_build/target_binaries # Directory where the final static binaries will be stored (the user must have write permissions here)
    source:
      main_repo: 
        git_url: https://github.com/virtualsquare/sshlirp
        build_system: cmake # Supported build systems: cmake, meson, autotools, makefile
      dependencies:   # List of APT packages to install inside each rootfs environment
        - pkg-config
        - libglib2.0-dev
        - libvdeplug-dev
      dependency_repos: 
        - git_url: https://gitlab.freedesktop.org/slirp/libslirp.git
          build_system: meson
          dependencies:   # List of APT packages to install inside each rootfs environment for this dependency
            - meson
            - ninja-build
            - libssl-dev
            - libglib2.0-dev
            - libexpat1-dev
            - libcap-ng-dev
            - libseccomp-dev
    build-config:
      build_mode: main  # Supported build modes: "main" (build only if the main repo has new commits), "dep" (build if any dependency repo has new commits), "full" (build if the main repo or any dependency repo has new commits)
      poll_interval: 3600 # Time interval (in seconds) between two consecutive checks for new commits
    architectures:  # List of target architectures for cross-compilation (all supported architectures are listed below)
      - amd64
      - arm64
      - armhf
      - riscv64